### ISSUE TITLE
IOS error

### ISSUE THREAD

**Issue by MeesterCor** [cranberrygame/cordova-plugin-ad-video-chartboost#2]
Added chartboost to my cordova project, on IOS i will get the same error over and over again:

chartboost.h file not found

What am i doing wrong?

**Comment by cranberrygame** [comment]
@MeesterCor 

for ios, use cordova cli like this:
cordova plugin add https://github.com/cranberrygame/cordova-plugin-ad-chartboost

Thanks

**Comment by MeesterCor** [comment]
Indeed i am using that exact commando to add the plugin to my ios project :(
What's wrong with it?

**Comment by cranberrygame** [comment]
@MeesterCor

I mean 
use not cordova-plugin-ad-chartboost
but https://github.com/cranberrygame/cordova-plugin-ad-chartboost
like following (use github) because of ios no symbolic link issue (cordova registry and https://www.npmjs.com/ (?)).

cordova plugin add https://github.com/cranberrygame/cordova-plugin-ad-chartboost

Thanks

**Comment by MeesterCor** [comment]
aah thanks :) its working

**Comment by cranberrygame** [comment]
@MeesterCor

Ok
